general:
  data_base_dir: /app/data
modules:
  UnsortedInstanceImporter:
    input_dir: input_data
  DataSorter:
    base_dir: /app/data/sorted
    structure: '%SeriesInstanceUID/dicom/%SOPInstanceUID.dcm'
  DsegConverter:
    dicomseg_json_path: /app/mhub/lungmask/config/meta.json
    skip_empty_slices: True
