dicomseg:
  BodyPartExamined: WHOLEBODY
  ClinicalTrialCoordinatingCenterName: dcmqi
  ClinicalTrialSeriesID: '0'
  ClinicalTrialTimePointID: '1'
  ContentCreatorName: IDC
  ContentDescription: Image segmentation
  ContentLabel: SEGMENTATION
  InstanceNumber: '1'
  SegmentAlgorithmName: TotalSegmentator
  SegmentAlgorithmType: AUTOMATIC
  SeriesDescription: Segmentation
  SeriesNumber: '42'
segments:
  AORTA: aorta.nii.gz
  BRAIN: brain.nii.gz
  COLON: colon.nii.gz
  DUODENUM: duodenum.nii.gz
  ESOPHAGUS: esophagus.nii.gz
  FACE: face.nii.gz
  GALLBLADDER: gallbladder.nii.gz
  INFERIOR_VENA_CAVA: inferior_vena_cava.nii.gz
  LEFT_ADRENAL_GLAND: adrenal_gland_left.nii.gz
  LEFT_ATRIUM: heart_atrium_left.nii.gz
  LEFT_AUTOCHTHONOUS_BACK_MUSCLE: autochthon_left.nii.gz
  LEFT_CLAVICLE: clavicula_left.nii.gz
  LEFT_FEMUR: femur_left.nii.gz
  LEFT_GLUTEUS_MAXIMUS: gluteus_maximus_left.nii.gz
  LEFT_GLUTEUS_MEDIUS: gluteus_medius_left.nii.gz
  LEFT_GLUTEUS_MINIMUS: gluteus_minimus_left.nii.gz
  LEFT_HIP: hip_left.nii.gz
  LEFT_HUMERUS: humerus_left.nii.gz
  LEFT_ILIAC_ARTERY: iliac_artery_left.nii.gz
  LEFT_ILIAC_VEIN: iliac_vena_left.nii.gz
  LEFT_ILIOPSOAS: iliopsoas_left.nii.gz
  LEFT_KIDNEY: kidney_left.nii.gz
  LEFT_LOWER_LUNG_LOBE: lung_lower_lobe_left.nii.gz
  LEFT_RIB_1: rib_left_12.nii.gz
  LEFT_RIB_10: rib_left_1.nii.gz
  LEFT_RIB_11: rib_left_10.nii.gz
  LEFT_RIB_12: rib_left_11.nii.gz
  LEFT_RIB_2: rib_left_2.nii.gz
  LEFT_RIB_3: rib_left_3.nii.gz
  LEFT_RIB_4: rib_left_4.nii.gz
  LEFT_RIB_5: rib_left_5.nii.gz
  LEFT_RIB_6: rib_left_6.nii.gz
  LEFT_RIB_7: rib_left_7.nii.gz
  LEFT_RIB_8: rib_left_8.nii.gz
  LEFT_RIB_9: rib_left_9.nii.gz
  LEFT_SCAPULA: scapula_left.nii.gz
  LEFT_UPPER_LUNG_LOBE: lung_upper_lobe_left.nii.gz
  LEFT_VENTRICLE: heart_ventricle_left.nii.gz
  LIVER: liver.nii.gz
  MYOCARDIUM: heart_myocardium.nii.gz
  PANCREAS: pancreas.nii.gz
  PORTAL_AND_SPLENIC_VEIN: portal_vein_and_splenic_vein.nii.gz
  PULMONARY_ARTERY: pulmonary_artery.nii.gz
  RIGHT_ADRENAL_GLAND: adrenal_gland_right.nii.gz
  RIGHT_ATRIUM: heart_atrium_right.nii.gz
  RIGHT_AUTOCHTHONOUS_BACK_MUSCLE: autochthon_right.nii.gz
  RIGHT_CLAVICLE: clavicula_right.nii.gz
  RIGHT_FEMUR: femur_right.nii.gz
  RIGHT_GLUTEUS_MAXIMUS: gluteus_maximus_right.nii.gz
  RIGHT_GLUTEUS_MEDIUS: gluteus_medius_right.nii.gz
  RIGHT_GLUTEUS_MINIMUS: gluteus_minimus_right.nii.gz
  RIGHT_HIP: hip_right.nii.gz
  RIGHT_HUMERUS: humerus_right.nii.gz
  RIGHT_ILIAC_ARTERY: iliac_artery_right.nii.gz
  RIGHT_ILIAC_VEIN: iliac_vena_right.nii.gz
  RIGHT_ILIOPSOAS: iliopsoas_right.nii.gz
  RIGHT_KIDNEY: kidney_right.nii.gz
  RIGHT_LOWER_LUNG_LOBE: lung_lower_lobe_right.nii.gz
  RIGHT_MIDDLE_LUNG_LOBE: lung_middle_lobe_right.nii.gz
  RIGHT_RIB_1: rib_right_12.nii.gz
  RIGHT_RIB_10: rib_right_1.nii.gz
  RIGHT_RIB_11: rib_right_10.nii.gz
  RIGHT_RIB_12: rib_right_11.nii.gz
  RIGHT_RIB_2: rib_right_2.nii.gz
  RIGHT_RIB_3: rib_right_3.nii.gz
  RIGHT_RIB_4: rib_right_4.nii.gz
  RIGHT_RIB_5: rib_right_5.nii.gz
  RIGHT_RIB_6: rib_right_6.nii.gz
  RIGHT_RIB_7: rib_right_7.nii.gz
  RIGHT_RIB_8: rib_right_8.nii.gz
  RIGHT_RIB_9: rib_right_9.nii.gz
  RIGHT_SCAPULA: scapula_right.nii.gz
  RIGHT_UPPER_LUNG_LOBE: lung_upper_lobe_right.nii.gz
  RIGHT_VENTRICLE: heart_ventricle_right.nii.gz
  SACRUM: sacrum.nii.gz
  SMALL_INTESTINE: small_bowel.nii.gz
  SPLEEN: spleen.nii.gz
  STOMACH: stomach.nii.gz
  TRACHEA: trachea.nii.gz
  URINARY_BLADDER: urinary_bladder.nii.gz
  VERTEBRAE_C1: vertebrae_C1.nii.gz
  VERTEBRAE_C2: vertebrae_C2.nii.gz
  VERTEBRAE_C3: vertebrae_C3.nii.gz
  VERTEBRAE_C4: vertebrae_C4.nii.gz
  VERTEBRAE_C5: vertebrae_C5.nii.gz
  VERTEBRAE_C6: vertebrae_C6.nii.gz
  VERTEBRAE_C7: vertebrae_C7.nii.gz
  VERTEBRAE_L1: vertebrae_L1.nii.gz
  VERTEBRAE_L2: vertebrae_L2.nii.gz
  VERTEBRAE_L3: vertebrae_L3.nii.gz
  VERTEBRAE_L4: vertebrae_L4.nii.gz
  VERTEBRAE_L5: vertebrae_L5.nii.gz
  VERTEBRAE_T1: vertebrae_T12.nii.gz
  VERTEBRAE_T10: vertebrae_T1.nii.gz
  VERTEBRAE_T11: vertebrae_T10.nii.gz
  VERTEBRAE_T12: vertebrae_T11.nii.gz
  VERTEBRAE_T2: vertebrae_T2.nii.gz
  VERTEBRAE_T3: vertebrae_T3.nii.gz
  VERTEBRAE_T4: vertebrae_T4.nii.gz
  VERTEBRAE_T5: vertebrae_T5.nii.gz
  VERTEBRAE_T6: vertebrae_T6.nii.gz
  VERTEBRAE_T7: vertebrae_T7.nii.gz
  VERTEBRAE_T8: vertebrae_T8.nii.gz
  VERTEBRAE_T9: vertebrae_T9.nii.gz
